name: Auto Update Poncho CSS

on:
  schedule:
    - cron: '0 9 * * *' # Todos los días a las 09:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar script de actualización
        run: python3 generate_cheatsheet.py

      - name: Commit y Push de cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git commit -m "Actualización automática de Poncho y regeneración de CheatSheet"; then
            git push
          else
            echo "No hay cambios para subir."
          fi
